CREATE DATABASE IF NOT EXISTS laravel_blog2 CHARACTER SET utf8 COLLATE utf8_general_ci;
USE laravel_blog2;

CREATE TABLE `entries` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `title` varchar(100) NOT NULL,
  `content` text NOT NULL,
  `user_id` bigint(20) UNSIGNED NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


INSERT INTO `entries` (`id`, `title`, `content`, `user_id`, `created_at`, `updated_at`, `deleted_at`) VALUES
(1, 'Qui necessitatibus.', 'Magni ut fuga odio. Sed facere facere consequatur animi veniam magnam voluptatum id. Optio cumque consequatur ut nesciunt quisquam qui. Nihil ipsam quia incidunt labore sequi dolore ullam natus.\n\nEarum et qui nesciunt voluptate dignissimos aut. Ut autem aut architecto magnam repellendus autem.\n\nSed nostrum quis est laudantium error non. Rerum et ut nihil debitis voluptas quis incidunt. Velit sed dolorem magnam magnam ut.\n\nImpedit temporibus iste sint voluptatem atque porro. Labore eligendi et ipsum et. Autem quo rem et et quis enim ab.\n\nDolorem sit aperiam sequi velit quam nihil soluta. Suscipit quaerat amet voluptatem adipisci aut est error. Explicabo quo et similique et placeat iste et.\n\nId aliquam molestiae illo doloribus nobis. Occaecati ipsum voluptas est rerum velit odio est aut. Rem culpa et officia.\n\nSunt ipsa dolores autem cum dolores autem dolor. Reiciendis recusandae molestias quia nihil.\n\nEt est in est fugiat. Velit rem accusamus est deleniti amet quia quia. Rem ut voluptatum perspiciatis praesentium consequuntur sunt aperiam non. Molestiae blanditiis qui vero quas. Dolore nobis reprehenderit commodi eaque.', 1, '2020-01-28 00:26:05', '2020-01-28 00:26:05', NULL),
(2, 'Qui qui.', 'Aspernatur eius et nesciunt incidunt perferendis. Qui facilis quo sapiente dignissimos ut omnis error. Vel aut qui adipisci quo incidunt voluptatem. Nihil qui est nobis veniam.\n\nMolestiae temporibus non quae voluptates libero eveniet ut optio. Id ad deleniti aperiam itaque eum. Laboriosam sed ut et dicta facere ut eos.\n\nId quo velit voluptates magni. Repellat maiores iste dignissimos corporis exercitationem doloribus dolore quia. Voluptatem dolorem vel similique quam. Eos repellendus suscipit laudantium hic impedit odio. Aut quis fugit ipsam aut consequatur voluptatem laudantium.\n\nAut saepe saepe similique labore quaerat. Sed omnis aspernatur corporis eaque molestias qui. Id magnam doloremque officiis at accusamus nemo. Sed consequatur iusto in incidunt et quae occaecati.\n\nSit dolorem magni et quia. Cumque harum velit beatae dolore eum sit. Dolorem repellendus unde quae eum earum perspiciatis consectetur. Eum ducimus quod esse vitae reprehenderit.\n\nAccusamus dolor vel ea vel sit recusandae. Quae ut vel debitis ea saepe dolores laboriosam provident. Quaerat quia distinctio id. Veritatis veritatis qui velit error deleniti sed quia. Reiciendis consequatur pariatur vel veniam.\n\nBeatae ab illo numquam. Ea assumenda dolore numquam ad. Commodi quae optio consectetur sequi et quos esse. Non et dolorem doloribus error.\n\nEius et dolore sed. Voluptatum quis magni dolorum iste sed aut eius. Minima voluptate et eaque natus. Tenetur porro maxime voluptatem.', 1, '2020-01-28 00:26:05', '2020-01-28 00:26:05', NULL),
(3, 'Enim molestias.', 'Et expedita sunt sit ut impedit. Quidem nobis amet consequatur odit animi optio asperiores. Inventore quaerat voluptates et in et ut nihil. Est tempore non hic molestias impedit et accusantium.\n\nSunt illum optio hic odit hic similique velit. Ut quidem id dolore laborum suscipit est rerum. Voluptas ducimus id eum qui.\n\nItaque facilis et in nostrum reprehenderit quia esse non. Tempora rerum aperiam eos iste ipsam. Sed minus quisquam fugit non dicta repellendus qui. Aut ut eum aliquid quos enim ab veniam.\n\nItaque aut sit sed qui enim deleniti. Autem expedita doloribus soluta illo rerum placeat. Necessitatibus doloremque repellendus voluptatibus maiores velit eligendi. Nihil facere sit occaecati perspiciatis.\n\nDolore consequatur tenetur qui delectus laborum sed. Ea et velit deleniti ut molestiae maxime numquam. At deleniti placeat quo dolor corrupti amet. Cum aut magnam fuga eaque.\n\nVoluptas animi laudantium dolor consequatur animi odit nesciunt. Qui necessitatibus ratione blanditiis voluptatem est id. Accusamus autem quisquam et rerum fugit libero. Ut hic veniam nostrum debitis similique illum.\n\nEt dolorem nihil et dolor voluptas ut. Possimus vero velit impedit ipsum in voluptas officiis. Nihil quis vel odio sint rem explicabo in.\n\nNon beatae eius et et voluptatum. Minus ullam explicabo repellendus aliquid occaecati expedita. Accusamus doloribus repellendus laborum incidunt.', 1, '2020-01-28 00:26:05', '2020-01-28 00:26:05', NULL),
(4, 'Fugit quia.', 'Et maiores odit et nihil. Veritatis veritatis a dicta maiores non. Magni aut quibusdam alias omnis quibusdam. In quia quia quo quas.\n\nNihil voluptatem tenetur porro voluptatem quidem sed consequatur. Est ea qui beatae dolor modi saepe veniam. Sed asperiores molestiae sunt asperiores earum est eum ut.\n\nMaiores vero adipisci minima nobis est distinctio eveniet. Commodi eos tenetur et nobis atque laboriosam consequatur.\n\nRem ut non consectetur blanditiis commodi odit omnis eius. Aliquam praesentium sunt reiciendis expedita modi. Eaque quae et autem quisquam doloribus. Autem aliquid corporis et et vero inventore.\n\nQuas commodi amet omnis aut impedit qui. Similique perspiciatis nemo quaerat voluptas nobis sed inventore. Quas sit recusandae maiores placeat et ab.\n\nVoluptas asperiores dolorem est praesentium dolores excepturi. Aut quo veniam eveniet et et provident et. Ipsam eos dolores qui doloremque aliquam. Illo minus laborum est autem eius nulla. Ex velit quod accusantium doloribus.\n\nMaiores explicabo velit consequatur dolor. Corporis corrupti ex fugit non nesciunt et aut architecto. Odit voluptas velit aut totam totam. Sint commodi corrupti nisi earum deserunt ratione nostrum. Modi porro architecto aut ipsam at.\n\nQuisquam eum perspiciatis iure enim vitae et sit. Id et animi vel qui eum ullam cum. Sit dicta cum eos dolor laborum fugiat. Sit sed deserunt tempora. Sunt quisquam voluptatem quos sit molestiae voluptas illum.', 2, '2020-01-28 00:26:06', '2020-01-28 00:26:06', NULL),
(5, 'Similique libero.', 'Deleniti et non ipsam voluptas aut neque dolores. Impedit exercitationem dolorum veritatis qui velit illum. Esse dolor assumenda et vel facere.\n\nFacilis optio enim est est. Excepturi et qui officiis corrupti et rerum. Distinctio quam atque et. Reiciendis nesciunt ab nobis quis sit fugiat ut.\n\nVoluptas sunt sed aut ea quisquam dolores perferendis. Ea assumenda officia id nihil est accusantium.\n\nEos iure excepturi molestias et veritatis quia. Repellendus vel ipsum voluptate non. Cupiditate minus totam praesentium maxime aut.\n\nTempore dolorem quae in sed. Labore fugiat consequatur sed ad. Nihil hic omnis voluptatem.\n\nQuia repellat iure quis aliquam. Et dolores aut culpa recusandae. Quasi dolores inventore inventore neque. Inventore mollitia unde perspiciatis et perspiciatis beatae. Sed assumenda expedita similique sit quisquam illum corporis.\n\nUt voluptas facilis modi vero in eum. Quia repudiandae ea perferendis perspiciatis aliquid fugit. Quasi excepturi ut excepturi esse earum explicabo.\n\nEveniet ea eligendi corporis aut. Magni aut culpa facilis corporis et. Placeat porro voluptatibus ad distinctio eum ipsum earum enim.', 2, '2020-01-28 00:26:06', '2020-01-28 00:26:06', NULL),
(6, 'Distinctio et ex.', 'Enim nam alias cum necessitatibus consectetur unde dolor. Saepe voluptatem voluptatem fugiat sunt reprehenderit sunt cupiditate. Tenetur neque alias deserunt sed voluptatem. Repudiandae est vero hic commodi voluptatum.\n\nUt occaecati ea quia odit nihil deserunt. Rerum corrupti autem quas quas quia impedit quis. Quae error dolorem quia ut corporis.\n\nDeserunt architecto excepturi suscipit inventore aspernatur quisquam. Aperiam ea iure consectetur minima sit. Repellendus eius deleniti officia nisi aut autem sapiente. Praesentium illo quidem voluptatem et debitis minima. Consequatur quam perferendis iste esse ex sit.\n\nVoluptatem qui aliquam est repellat voluptatem. Aspernatur voluptas expedita accusamus necessitatibus nemo est maxime. Dolorum quaerat laudantium velit rerum nesciunt nulla.\n\nAutem accusantium ut consequuntur. Sit magnam officiis odio. Commodi magnam aliquid harum velit eveniet iure.\n\nDoloremque vel soluta maxime sit illo. Quae tenetur et tenetur vel. Sit dolores voluptatem provident voluptatem.\n\nAut fugiat quasi quibusdam dolor blanditiis quaerat vel. Aut rem facere quam quibusdam magnam nisi autem porro. Aut rerum incidunt adipisci aut commodi quod blanditiis.\n\nQui fuga modi aut vero eligendi. Aut id doloremque sed a. Natus et sequi est sit maxime.', 2, '2020-01-28 00:26:06', '2020-01-28 00:26:06', NULL),
(7, 'Cupiditate iure cum.', 'Dolores ut est eaque ut. Commodi aut quasi alias. Aspernatur reiciendis sint eaque perferendis eum id. Omnis tempora quo omnis aut repellendus omnis nostrum omnis.\n\nQuia autem ea ex in inventore doloremque culpa nobis. Ut cum consequatur ipsam qui. Quia et et corporis rem illum ea aliquid.\n\nAtque minus ratione qui accusantium. Amet vero quidem qui sit non dolore. Eligendi est enim voluptate ex aut et id ut.\n\nSit hic sed doloribus ut laudantium. Animi vero aut dolor inventore et dicta dolores. Ipsa voluptas adipisci voluptates consectetur deserunt molestiae. Quo consequatur reiciendis aut.\n\nSaepe cum sit rerum qui. Reiciendis sint sed sed quia neque. Aliquid ut cum occaecati quia saepe. Culpa non accusamus iure. Aut ut porro sint quod praesentium.\n\nRepellendus id quo a voluptatibus est voluptatem. Ut minima consequatur earum voluptatem recusandae repellat.\n\nLaboriosam quaerat expedita aliquam culpa molestiae porro ut. Fugit est suscipit delectus iure vero quod quae. Qui numquam aut temporibus corrupti laudantium odit. Ut recusandae voluptatum harum praesentium voluptatem.\n\nSit fugiat voluptate iure ducimus cumque. Eaque nemo hic voluptas autem ut.', 3, '2020-01-28 00:26:06', '2020-01-28 00:26:06', NULL),
(8, 'Similique est est.', 'Quisquam molestiae asperiores maxime repudiandae qui. Sunt modi hic ipsum architecto velit in molestiae soluta. Nostrum maxime velit enim sed corporis quae. Voluptatibus eaque est quia.\n\nArchitecto nulla ad non nam quam ad. Veritatis incidunt pariatur quam dolorem a. Assumenda harum id mollitia ipsam alias expedita harum dignissimos.\n\nEst numquam similique libero ut omnis maiores qui. Voluptatem saepe voluptatum fugit ad voluptatibus. Nesciunt voluptatem sint voluptatem. Et mollitia doloremque tempora commodi exercitationem est doloremque.\n\nAt aut dolorem consequuntur sunt veniam distinctio sunt. Aut quisquam exercitationem voluptas voluptas vel et. Et recusandae possimus veniam autem. Impedit suscipit sit tenetur incidunt.\n\nAccusantium quos occaecati distinctio suscipit tempora dolor quaerat. Quisquam ad saepe qui assumenda. Voluptatem labore quidem facere.\n\nEst eligendi quidem reprehenderit. In sed est rerum voluptate. Eius aut neque deleniti quis.\n\nOccaecati ipsa aperiam vero non fugit harum esse ipsum. Eos ab velit harum voluptatum. Eius et totam quaerat pariatur voluptates asperiores.\n\nAtque in qui minus corporis. Aut ea nihil velit. Dolores nesciunt sit maiores.', 3, '2020-01-28 00:26:06', '2020-01-28 00:26:06', NULL),
(9, 'Et ducimus.', 'Omnis enim voluptatem repellat illum. Porro dolorem voluptas nam quia rerum facilis sed. Aut itaque et voluptatem dolorem.\n\nMolestias nobis dolorem amet nemo illum. Sed et ab corrupti veritatis excepturi. Voluptate commodi consequatur sint culpa et odit fugiat.\n\nNihil aspernatur distinctio dolores iusto laboriosam dicta. Qui aut tempora explicabo illum quas in qui. Maxime et et quis.\n\nIpsum atque et inventore ut. Ab inventore provident quos eum tempora quia. Est neque blanditiis nisi deserunt.\n\nTotam provident nisi fugiat aspernatur doloremque deleniti. Dignissimos non libero dolores aliquid quos officia optio. Consectetur vel nostrum vel soluta dignissimos maiores officiis. Officia est voluptas minima qui officiis tenetur.\n\nProvident deleniti adipisci ea sequi molestiae culpa. Incidunt laborum eaque non ullam dolore facilis nihil ut. Vel repudiandae pariatur blanditiis quam quas autem. Consequuntur qui molestias commodi.\n\nVoluptatem consequatur eaque itaque suscipit natus vitae. Amet et quaerat mollitia quis consequatur.\n\nUt praesentium consequatur et porro cupiditate. Nihil illo commodi consequatur quo. Ab sed saepe harum nihil fugiat ut pariatur nobis. Eius dolores ex non esse.', 3, '2020-01-28 00:26:06', '2020-01-28 00:26:06', NULL),
(10, 'Laborum laudantium.', 'Rem culpa veritatis at quibusdam quod. Excepturi laborum vero repellendus nobis libero qui qui. Porro ut quia voluptas nisi quidem accusantium blanditiis.\n\nEt eos quia asperiores nobis sed pariatur. Est quae incidunt nobis quia modi vero soluta minima. Non labore quidem reiciendis. Esse non molestiae odit dolores.\n\nAlias non atque unde explicabo beatae. Sint molestiae omnis dolorem blanditiis placeat nulla. Sed aliquid nisi aliquam.\n\nOfficia est non dolorem. Saepe eaque qui iure fugiat qui. Libero veritatis aut molestiae ipsa aspernatur vel omnis.\n\nRepellat unde assumenda harum fugiat necessitatibus amet quae. Consequatur et est voluptate facilis. Ad sit suscipit maxime quisquam commodi. Nihil tempore repellendus quibusdam cum aspernatur aperiam quaerat.\n\nIllo est ducimus fugit repellat ipsam est qui ut. Molestias autem quia deserunt debitis excepturi. Voluptatem non natus eos.\n\nEst dolor iusto explicabo enim est. Sint quam recusandae blanditiis laboriosam illo ad sint. Atque voluptatibus quae nemo quidem. A sequi repudiandae sequi.\n\nSed nobis voluptates nihil. Non et mollitia nesciunt ut odio facere nihil. Numquam iure inventore sint ex.', 4, '2020-01-28 00:26:06', '2020-01-28 00:26:06', NULL),
(11, 'Voluptas pariatur.', 'Nobis quae necessitatibus cumque. Aspernatur accusamus cupiditate laborum architecto dolores facilis. Et sapiente aperiam rerum provident. Perferendis ut sit expedita ex impedit eius.\n\nVoluptatibus ipsa natus veniam enim alias. Eveniet qui quos possimus esse qui nisi. Labore sequi ex id ad laudantium aut.\n\nAmet quam sint accusantium placeat voluptatem. Voluptas quae vel fuga voluptates labore. Qui et sed incidunt maiores id. Pariatur est possimus et.\n\nAliquam in incidunt et impedit tempore nesciunt labore. Iusto nulla asperiores quo occaecati eius iusto molestiae quos. Aspernatur odio perferendis qui at dolores deleniti.\n\nFuga iste ex animi commodi quod. Non dolorum similique autem. Est quas voluptas similique omnis modi. Ipsam est neque error et blanditiis vel reprehenderit.\n\nIusto corporis officia sit. Ut nihil sunt facere consectetur et ex. Excepturi qui corrupti beatae quia quia fuga reiciendis.\n\nAccusantium delectus reprehenderit in placeat eius. Reiciendis perferendis ut nam necessitatibus aspernatur et ipsa. Adipisci dolorum eaque quibusdam et minima neque.\n\nMaxime consequatur nemo cupiditate qui dignissimos sed. Doloremque ut maiores et quibusdam nemo amet magni. Recusandae quas aliquid fugiat dolor suscipit a quas.', 4, '2020-01-28 00:26:06', '2020-01-28 00:26:06', NULL),
(12, 'Corporis itaque.', 'Ea tenetur ad placeat repudiandae explicabo natus. Culpa dolore voluptas est enim consectetur. Omnis nam aut tempora et eius assumenda autem consequatur. Quo esse dolores esse accusantium tempore magni dignissimos dolorum.\n\nModi quibusdam qui mollitia aut cum. Dolorum nisi asperiores et blanditiis.\n\nSunt mollitia quam qui vero. Tenetur fugiat temporibus voluptatem et sed. Cumque aperiam architecto aut commodi natus et. Molestias quas explicabo voluptatem.\n\nDucimus repellendus corrupti commodi impedit omnis officia illo ut. Et sunt natus maiores ratione. Sunt doloribus temporibus eligendi libero laudantium. Eos est nobis iste sapiente.\n\nEum voluptatem quas qui repellendus distinctio doloremque. Omnis illum vitae accusantium perferendis est. Voluptate reiciendis doloribus ut ea repellat velit dolorem eaque.\n\nNihil sunt animi non sed ratione. Illo ut consequatur quae quos. Et minima eius sunt consequatur ut.\n\nIllo veniam deleniti temporibus excepturi placeat cum. Veniam possimus voluptatem aut et beatae. Rerum occaecati optio quisquam eaque.\n\nSit excepturi dolorum voluptatem nulla qui. Voluptatem occaecati ut ratione velit veritatis dolores. Cupiditate nesciunt exercitationem voluptas placeat. Voluptas iste vitae eum.', 4, '2020-01-28 00:26:06', '2020-01-28 00:26:06', NULL),
(13, 'Tempore alias alias.', 'Et magni blanditiis cum assumenda. Aut eos ratione dolorem aliquam repellendus doloremque. Optio reprehenderit hic ipsa porro autem. Nihil autem cumque nisi vero eaque. Sit aut sapiente laboriosam harum vitae eius.\n\nSint aut non accusamus dolor commodi. Quis hic veniam laudantium iste earum ipsum itaque.\n\nQuos mollitia blanditiis atque sunt nesciunt saepe est. Rem consequatur modi commodi occaecati ea omnis. Rem delectus aliquam magnam. Vero et commodi error.\n\nAnimi occaecati iusto sint et rerum et modi. Eos velit aut eum nulla porro explicabo aut. Nihil laborum optio veniam odio. Debitis deleniti porro impedit architecto. Quia enim cum molestiae sint nisi laudantium nemo.\n\nUt est quam ratione id. Iure suscipit quas est dolorem. Ea ipsum neque sapiente modi est. Nostrum itaque vitae est.\n\nQuod ut est ex magni expedita. Id adipisci illo qui temporibus ullam facilis laborum. Aut enim ad quo ipsa.\n\nFacilis totam blanditiis itaque quo numquam vel. Velit eum qui dolores quasi quidem. Fugiat quo repellat et sint nemo excepturi. Similique omnis aut similique voluptatem nobis.\n\nAtque libero dolorem non consequatur ea. Pariatur aperiam consequatur aut voluptas aut eveniet. Et deserunt omnis accusamus quos. Ut impedit aut minus animi praesentium amet. Dolorem voluptatem dolorem provident vel mollitia.', 5, '2020-01-28 00:26:06', '2020-01-28 00:26:06', NULL),
(14, 'Quos non quasi est.', 'Unde animi ut autem incidunt numquam harum. Deleniti est quod quia odio modi cumque tempora. Quas perspiciatis libero dolorum qui id tempora facilis.\n\nVero quis architecto qui adipisci. Quia qui perspiciatis est et impedit aperiam sed voluptatem. Qui dolor omnis velit quasi est. Modi et culpa iste a suscipit rerum. Eum minus aut enim ut velit ut laboriosam quaerat.\n\nEveniet aut est distinctio. Dolorum eaque nihil impedit dolorem expedita eaque officia. Est perferendis perspiciatis expedita consequatur magnam et illum sint.\n\nQuis a molestias omnis laudantium. Aspernatur maxime vel architecto occaecati ut omnis. Earum a quia non velit asperiores voluptas dolor.\n\nLaboriosam saepe iure veniam commodi odit pariatur. Tempore inventore nemo omnis ab iste ipsam non nulla. Similique qui facilis et officiis aut. Quo qui incidunt aut voluptates error ad.\n\nDoloribus ipsum natus quia quis sapiente quaerat eos tempore. Neque consequatur deserunt sed aliquam pariatur et culpa. Velit aut omnis voluptate quas delectus. Minima quis et quasi natus.\n\nIllo consequuntur dolorem laboriosam voluptatem nihil fugiat. Suscipit est ut et harum eos. Doloremque temporibus mollitia distinctio est. Quas fugit ea qui voluptas omnis.\n\nHic adipisci impedit voluptatem et ut. Doloribus dignissimos est et. Quae et ab qui autem. Delectus minus et suscipit.', 5, '2020-01-28 00:26:06', '2020-01-28 00:26:06', NULL),
(15, 'Aliquid dolore aut.', 'Voluptas voluptate eligendi quae est esse ipsa. Quo rerum nulla sed. Voluptas voluptatibus minus minus non quod repellat unde. Quis porro dolorem unde assumenda asperiores a.\n\nEius in aut cumque odio. Non molestiae commodi reiciendis rerum. Non possimus inventore error similique qui consequatur. Corrupti necessitatibus harum voluptates a ea qui. Ad nesciunt maxime perspiciatis voluptatem sapiente accusamus repudiandae.\n\nQuis et eius nulla nihil. Tempora modi sint rerum repudiandae. Laudantium non nihil officia sunt dolore ab.\n\nExplicabo eos modi aut ullam iusto fuga consequatur mollitia. Et sed incidunt provident ipsa. Adipisci architecto ad tempora natus ut quia est quia.\n\nSoluta voluptatem ipsam tempora eaque vel odio. Quod quasi dolorem nostrum neque ipsa distinctio debitis. Eum aut quas inventore provident.\n\nAut ullam ea minus expedita est. Labore qui esse ab ut ipsum. Aperiam et eius aut veniam accusantium est.\n\nSit voluptatibus ab quibusdam eius a ratione. Delectus quod mollitia voluptas ea eos. Voluptates sunt id qui et rerum eos soluta.\n\nDolore cumque non assumenda pariatur enim. Necessitatibus quaerat enim sed minus molestias. Ab qui expedita sed repudiandae magni velit.', 5, '2020-01-28 00:26:06', '2020-01-28 00:26:06', NULL),
(16, 'Sint optio in est.', 'Qui exercitationem dicta consectetur fuga deleniti rerum asperiores. Itaque voluptatem fugiat facilis quia. Voluptatem a ex voluptas sequi facere maiores quis.\n\nEx animi aperiam qui voluptatem rerum. Hic et eum ut quia. Ex veritatis nemo cumque temporibus quibusdam velit. Eum modi rerum voluptatibus quibusdam non et eaque laborum.\n\nLaborum eaque harum qui labore. Cupiditate sequi magni sapiente aut occaecati. Ullam ab doloribus optio fuga ex harum.\n\nVoluptates eos magnam in dignissimos placeat facilis. Dolorum rerum mollitia voluptate voluptate qui. Voluptas pariatur qui blanditiis vero dicta ea consectetur.\n\nFacilis molestiae quas accusantium distinctio ut et dolor. Nemo aliquam voluptates impedit ut consequatur ut.\n\nLaborum ratione omnis magni quaerat quasi error repellendus. Aut asperiores est praesentium animi sunt numquam exercitationem. Quaerat nobis quidem suscipit. Impedit velit consequuntur consequatur corporis aut voluptatum.\n\nSaepe quo repudiandae nemo qui corrupti sit ducimus. Rerum qui alias ut quasi quis. Qui dolor facere doloribus distinctio omnis. Consequatur ut vel voluptatem doloremque dignissimos.\n\nQuia ut et minima dolorum. Accusamus laudantium voluptas dolorum dicta enim. Occaecati non quaerat sunt pariatur.', 6, '2020-01-28 00:26:06', '2020-01-28 00:26:06', NULL),
(17, 'Animi aut.', 'Et magni fugit autem voluptatem deleniti. Et mollitia deleniti tempore minus consequatur et. Ab qui eaque modi sit quia.\n\nEt qui tempore dignissimos. Voluptates illum et ipsam sit ea. Exercitationem tenetur accusamus vel sapiente. Et enim et qui corporis excepturi consequatur dolorum. Nobis voluptates omnis nulla et expedita numquam aut.\n\nEnim consequatur eligendi hic qui. Omnis perferendis rem doloremque. Eligendi nesciunt et consequatur delectus dignissimos cum fugit itaque. Temporibus fugiat quia eos soluta aut aut.\n\nOmnis dolorum alias aut aut cupiditate. Et illum laboriosam eos ipsum. Consequatur consequatur sit laborum ab eius repellendus.\n\nQuod rerum non corporis voluptatibus possimus in ipsum quisquam. Blanditiis qui et consequatur magnam eius vel odio. Facere omnis laboriosam numquam dolores dolor impedit soluta.\n\nAssumenda molestiae incidunt voluptatem iste ratione. Reiciendis nisi porro temporibus dolorem.\n\nEsse animi vel sunt harum culpa sed temporibus. Et sit et sint. Impedit quisquam nulla non. Aut ut autem iure fugiat nobis omnis optio.\n\nDolorem omnis et id consequuntur. Sed exercitationem aut sapiente voluptatum magnam est sed magni. Exercitationem aspernatur recusandae vitae eius molestiae ab quo.', 6, '2020-01-28 00:26:06', '2020-01-28 00:26:06', NULL),
(18, 'Alias et sit.', 'Nihil et magni enim distinctio enim. Cumque tempora modi quis et. Nihil dolorum voluptatem aut corporis. Inventore ratione omnis quos maiores natus laboriosam corrupti.\n\nFugit dolorem dolorem tempora blanditiis. Enim at vel omnis distinctio saepe quasi. Ratione dignissimos tempore sunt et nisi et omnis blanditiis. Aliquam voluptas odio magnam voluptas quis voluptas veniam.\n\nVel fugit quis ex necessitatibus earum sint. Quasi temporibus dolor enim ut dicta minima. Voluptatem exercitationem aut ex deleniti ipsa incidunt fugit non.\n\nIpsa doloribus non reprehenderit sapiente praesentium et. Ratione voluptatem vel saepe ab nobis iusto. Et eveniet ut voluptatem rem nam tempora.\n\nVitae qui et voluptatem voluptas nihil ut eum consequatur. Et voluptas quia nesciunt. Rerum sit est consequuntur ea ut hic.\n\nNihil facilis consequatur et dolorum molestias. Et accusamus consequatur qui aliquid dolor exercitationem. Architecto in rem aut nemo.\n\nEum aspernatur quidem aliquam facere. Tempora expedita dolore consequuntur minima. Qui nihil dicta omnis quia. Ipsam nobis aut illo eaque.\n\nAnimi voluptatibus perferendis sapiente dignissimos et explicabo sapiente. Aut asperiores fugiat id placeat sint. Ipsum odit autem voluptas rerum.', 6, '2020-01-28 00:26:06', '2020-01-28 00:26:06', NULL),
(19, 'Sed perspiciatis.', 'Ut dolores distinctio ut distinctio quia. Omnis ad quis illum enim qui in non. Laborum dicta aut omnis nisi. Id ut porro velit ut repellat sint alias.\n\nEt nobis rerum id est praesentium non nobis. Consequuntur ducimus omnis consequatur id omnis. Labore eos consectetur quo earum perferendis.\n\nQuod nihil harum voluptas odit est alias. Quisquam distinctio sed harum voluptas est. Quia possimus cum qui omnis maxime omnis atque. Quia dolorem pariatur sed.\n\nEa commodi qui quam et sequi consequatur quis. Nisi voluptatibus tempora debitis praesentium aut et. Aliquid et odio neque laborum voluptates. Voluptatibus impedit laborum ut autem.\n\nSaepe quaerat minus quaerat rerum veritatis quam recusandae recusandae. Ex molestias tempora eius eaque placeat incidunt ut. Quo minus rerum nam laboriosam sint.\n\nReiciendis facilis ducimus explicabo enim et. Aut repellendus omnis eius eum. Quidem aperiam laboriosam magni inventore id. Delectus quibusdam quia et rerum voluptas nisi in.\n\nEt voluptas velit est eum. Totam cum ullam in illo.\n\nQuos esse reiciendis ut ipsum cum assumenda. Laudantium aut sit voluptate eos laborum qui impedit. Deserunt sequi corporis nisi sunt vitae eaque a consectetur. Quis et optio dolores.', 7, '2020-01-28 00:26:06', '2020-01-28 00:26:06', NULL),
(20, 'Accusamus dolorem.', 'Omnis est et quibusdam enim qui. Non deserunt voluptatem quisquam non. Tempora quia ipsum aut reiciendis molestias.\n\nEx voluptate tenetur aut modi fugit. Deleniti saepe minus ut id veniam dolores. Nisi consequuntur repellat laboriosam eos. Esse est praesentium incidunt laborum.\n\nAssumenda cum quod iusto ex dolore. Odit ut voluptatem consequatur magnam cupiditate repudiandae. Cupiditate assumenda accusamus aperiam.\n\nEius excepturi molestias vel qui rerum sit. Et qui maxime possimus ut. Necessitatibus atque laudantium nobis aut sed vero harum. At facere porro molestias possimus odit nulla amet.\n\nFacilis velit saepe blanditiis voluptatum ut nihil laboriosam. Dolorem quia sit doloribus aliquid. Sed quos eum in laudantium quaerat excepturi in vel. Molestias repellendus minima vero inventore fuga aliquam.\n\nSed qui minima deserunt accusamus. Et animi qui libero numquam beatae perspiciatis. Et assumenda assumenda qui in nobis dolores possimus. Enim id qui aliquid odio.\n\nTempore sit ut placeat est quia eum nesciunt est. Occaecati id et consequuntur quibusdam doloribus eum. Ea labore perspiciatis molestias corporis ipsa ut cum officiis. Fugit velit illo non aut.\n\nQui eveniet harum hic aliquam aut voluptatibus illum debitis. Quos eum repudiandae et qui. Minima tempora quos ipsa vero. Explicabo amet distinctio facilis autem.', 7, '2020-01-28 00:26:06', '2020-01-28 00:26:06', NULL),
(21, 'Tempora culpa sint.', 'Asperiores quo in maxime aperiam voluptatem sed. Necessitatibus repudiandae praesentium ut velit. Asperiores rerum aliquam qui omnis quis animi.\n\nSit deserunt numquam consequuntur qui. Doloribus est possimus dolor. Provident molestiae qui molestiae necessitatibus ea.\n\nNostrum unde excepturi molestiae deserunt. Repellat eos voluptatibus enim. Sunt est laudantium maxime laudantium ducimus rerum dolorum.\n\nOptio perspiciatis culpa alias placeat. Odio sit dolorem ipsa aspernatur incidunt. Rem quibusdam deleniti quis. Ex quos quia placeat perspiciatis ut enim.\n\nDolorum et dolores cumque sed. Magni doloremque nemo magnam sed beatae voluptatum eius. Repellat blanditiis pariatur enim.\n\nDolorem ut velit quisquam quia ex in veritatis qui. Rerum dignissimos magnam nobis dolorem earum corrupti. Aliquam provident mollitia at in molestiae aut. Amet corrupti aut eius quos.\n\nRerum laudantium eos iste nihil. Optio et hic nisi. Pariatur debitis dolores id eos et. Impedit tenetur distinctio veniam quod similique. Dolor dolorem et omnis aliquam eos facilis possimus.\n\nQuo vero laboriosam unde sed sunt. Qui laborum laborum voluptatibus quis. Voluptate veniam iste fugiat odio.', 7, '2020-01-28 00:26:06', '2020-01-28 00:26:06', NULL),
(22, 'Necessitatibus aut.', 'Qui optio quo blanditiis iste et. Nesciunt nisi fugiat voluptas distinctio. Ad soluta et vero eum exercitationem. Sed et aspernatur nulla sit neque.\n\nQui illo culpa recusandae facilis id et quia. Sit dolores nam ipsum reiciendis et officiis. Adipisci necessitatibus similique illo temporibus aut. Consectetur quibusdam fuga odit et. Est et et eos est dicta consequatur.\n\nAut molestias eum in labore reprehenderit eos. Aut quo optio ut sit. Aut architecto nihil accusamus similique ducimus voluptas. Beatae omnis unde ut voluptatem est nam.\n\nCum libero tempore tempore id qui maiores sequi. Repudiandae natus similique voluptas quaerat labore sed vitae. Aliquid rem autem optio porro sit reiciendis aut similique. Dolores vel sed quo rerum nam aut minima.\n\nPorro vitae et officia. Consequatur voluptas soluta pariatur labore dolores et. Dolorem magni rerum inventore.\n\nEst aut rerum est in. Labore mollitia architecto qui nostrum doloremque repudiandae earum. Laborum dolorem nemo sunt animi ut quasi. Est exercitationem ipsum et ratione corporis quibusdam.\n\nReiciendis aliquid quos molestiae dolore. Tenetur sit magni eius rerum suscipit quia tempora. Deserunt dolore eligendi sit sapiente.\n\nNon voluptatem optio qui dolorem. Assumenda omnis distinctio nesciunt sed ut. Alias ullam dolorum omnis. Temporibus vitae quam quo et dolore vero illum.', 8, '2020-01-28 00:26:06', '2020-01-28 00:26:06', NULL),
(23, 'Consequatur et.', 'Repellat pariatur sint doloribus tempora ipsam. Ut libero voluptatibus omnis possimus. Nisi voluptas non totam soluta dolorum velit. Itaque voluptatem autem consequatur est eos.\n\nEsse quae quis et non molestiae ad aliquam rerum. Iure distinctio quibusdam sequi praesentium. Ut earum numquam culpa voluptatibus quod.\n\nEt et quia rerum voluptatem autem quia. Sequi libero quia neque id omnis reprehenderit. Ipsa eum et nesciunt.\n\nNecessitatibus neque ea quis rerum quisquam officia pariatur. Doloremque minus aliquam quam quidem. Ut dolorem quo perferendis amet.\n\nQuia ipsa quia voluptas asperiores vel dignissimos. Eum adipisci vitae perspiciatis ut itaque deleniti hic. Qui itaque deleniti enim consequuntur et qui beatae. Asperiores vel ea quasi alias amet. Ducimus dolor et consequatur dolorum repellendus velit libero.\n\nExercitationem quidem at dignissimos sed eveniet. Debitis dignissimos ex dicta sit culpa ducimus. Nulla placeat exercitationem quae quis.\n\nNihil voluptatibus omnis incidunt porro. Incidunt hic accusamus possimus at. Minus ea dolorem libero delectus non iste. Non minus praesentium blanditiis quasi enim aliquam ullam.\n\nEaque quod suscipit quae officiis libero et. Sed vitae illum nesciunt debitis. Animi libero culpa facere aliquam est. Itaque iure quia dolorem debitis est occaecati ratione.', 8, '2020-01-28 00:26:06', '2020-01-28 00:26:06', NULL),
(24, 'Amet omnis quo.', 'Vero sequi adipisci unde aperiam. Voluptas repellat neque eius sed dolorem qui. Ut quis modi sunt qui. Est ipsa et mollitia.\n\nDolores tenetur aut aspernatur sit possimus repudiandae. Amet consequatur incidunt veniam maxime voluptatem labore autem. Rerum adipisci tenetur eos ut. Rerum repellat quaerat et sed dolor sed.\n\nTempore possimus et possimus et corporis. Dolore aut officiis ipsa incidunt enim. Illum neque omnis esse eos eius saepe esse. Non sed asperiores officiis quo.\n\nReprehenderit sunt consequatur mollitia sit laboriosam cum maiores. Non nihil laudantium quia reiciendis qui voluptas labore perferendis. Quae expedita ullam nulla quod sit molestias adipisci. Qui recusandae perspiciatis nobis et quibusdam sunt.\n\nUnde quod commodi est eos. Eius minima alias laudantium veritatis qui veritatis. Ut omnis minus ducimus velit.\n\nTotam molestiae sit culpa possimus quia voluptatem a qui. Sunt et repellat enim qui porro.\n\nSunt quia dignissimos dolor quis. Quia ut rerum dignissimos qui maxime quos perspiciatis. Consequatur magnam voluptatem praesentium dignissimos modi excepturi quisquam et. Sequi at soluta perspiciatis impedit dolores. Incidunt error magnam eius omnis a voluptates et quas.\n\nRerum esse doloribus cumque et quibusdam iste quia provident. Laborum qui sint temporibus numquam ipsum vero nesciunt. Doloribus natus in commodi. Quod est maiores hic.', 8, '2020-01-28 00:26:06', '2020-01-28 00:26:06', NULL),
(25, 'Asperiores corrupti.', 'Vitae aut necessitatibus placeat ex earum. Debitis odit non sequi in quia. Et iusto quisquam ducimus ut. Quos deserunt harum tempora omnis autem quae.\n\nOdit laboriosam dolores nesciunt alias rerum eligendi. Sequi inventore aut voluptas similique sapiente expedita. Atque ullam veritatis natus omnis voluptatum nostrum sit. Rerum expedita repellendus quo totam dignissimos est quaerat.\n\nExplicabo laudantium sapiente rem. Corporis sequi doloremque vel vitae ratione cupiditate quia. Eos repudiandae est voluptatem.\n\nAutem eius illum consequatur. Perspiciatis voluptatem blanditiis minus officiis et quod. Vel ut molestiae quia. Aut explicabo sunt quod consequatur ut a quasi.\n\nLaboriosam aliquam quaerat molestiae non dolores et at. Expedita quod rerum est sed est quae voluptatem. Quos natus a dolorem debitis et eum vel. Et maiores dolorem consequatur exercitationem laudantium et fugiat.\n\nBeatae et corrupti quia consequatur rerum. Temporibus ducimus nam recusandae sint occaecati. Aspernatur unde laborum molestiae dolores.\n\nPossimus est est ducimus tempora. Aut qui cupiditate error. Fuga laudantium fuga omnis nisi et. Dolore explicabo sapiente sit tenetur.\n\nVoluptas consequuntur commodi similique aut ut. Sequi adipisci rerum excepturi corporis illo quidem possimus tempore. Repudiandae est eos vel.', 9, '2020-01-28 00:26:06', '2020-01-28 00:26:06', NULL),
(26, 'Suscipit sunt.', 'Ut ut voluptatem eos et unde iure suscipit. Enim repellendus quos ducimus voluptates porro repellat et. Saepe non nam quisquam non voluptas non odio. Velit nihil aperiam cupiditate est dignissimos facilis.\n\nNon possimus ad quia. Illum possimus dolor sed a. Dignissimos aperiam est ipsam doloremque.\n\nQui similique non dolores odit cumque. Tempora eaque vel accusamus amet assumenda cum. Assumenda quasi deleniti sit deserunt.\n\nId accusamus est odio similique alias. Voluptates ut consectetur hic omnis ut sed rerum. Praesentium illo et nisi consequatur cumque deserunt ullam. Rerum repudiandae pariatur distinctio adipisci earum qui.\n\nRerum ad harum tempore ad. Ipsam ab provident voluptas. Necessitatibus sit maxime et sint error. Sed debitis modi aperiam ad illo.\n\nVeniam aut voluptatem veniam aut officia. Deleniti quaerat quia quia iusto. Aut rem voluptatem ut sed fugit quo. Ipsum temporibus tempora a.\n\nAb sint officiis modi doloribus ratione nihil consequatur. Sed amet ullam laboriosam impedit.\n\nEt at quam incidunt voluptatibus quis. Et et minus eum corporis. Est dolorem pariatur minima. Et alias esse excepturi earum ut doloribus quos nobis.', 9, '2020-01-28 00:26:06', '2020-01-28 00:26:06', NULL),
(27, 'Molestiae aliquam.', 'Deleniti eligendi ipsa qui autem nisi autem sit. Dolores nostrum neque ut dolore maiores repellendus voluptatibus magni. Ad tempore et perspiciatis qui labore.\n\nEt quia est recusandae quasi unde. Autem quam neque mollitia quis pariatur. Dolor sit veniam voluptatem dolorem.\n\nCorporis autem sunt eligendi reiciendis. Dignissimos odit autem distinctio esse. Sint corporis dolore qui exercitationem excepturi nisi praesentium. Magni accusamus ea non est doloribus voluptatem. Voluptatibus magnam perspiciatis qui et iusto.\n\nMollitia modi earum illo ut nemo laborum. Dolor dolor optio molestiae. Qui enim qui laborum doloribus sequi. Non harum voluptatum repellat aperiam delectus qui.\n\nLibero quia dolor rem similique. Dolorem sapiente ut sed repellendus aut impedit ducimus quia. Nobis possimus vel qui laboriosam delectus.\n\nIllum iure hic omnis autem vel ex. Quasi a id odit. Debitis provident beatae similique eligendi voluptates voluptatum tempora eum.\n\nEum consectetur voluptatibus id nulla eius. Ratione fugit sit nam iste sunt voluptas. Quos possimus facere totam natus enim accusantium. Atque neque omnis modi.\n\nQuia fugiat voluptatem magnam est voluptas officiis. Iste et qui nesciunt quia aut maxime corporis. Sequi ea libero dolores aut fuga nobis sed.', 9, '2020-01-28 00:26:06', '2020-01-28 00:26:06', NULL),
(28, 'Sed numquam.', 'Repellendus dolore quod est totam praesentium error ducimus debitis. Consectetur eum dolor culpa sint dolores. Aut est consequatur aut doloremque vel nam. Alias voluptatum quam velit non itaque id.\n\nVoluptate voluptatem impedit iste. Numquam voluptatum quas velit laborum. Et non maiores sit repudiandae ea in dolor repellat.\n\nDistinctio et eos molestiae odio et sit perferendis. Ut hic enim repellat ipsa voluptate assumenda. Repellendus et qui optio eum quia reprehenderit.\n\nAmet a est amet quidem aliquam. Quia rerum inventore aut veniam laborum. Numquam saepe corrupti accusamus. Quia dolor impedit et.\n\nFacilis velit omnis tenetur sit cumque consequatur perspiciatis neque. Sit unde laudantium sed rem optio consequatur. Voluptatem placeat quis voluptatibus qui ratione quae.\n\nQui a voluptas quasi. Quo doloribus et facere et nostrum. Minima deleniti voluptatem voluptatibus iste possimus velit omnis.\n\nTempora saepe minima eos asperiores sed distinctio ea. Eius voluptate error aperiam qui et. Assumenda quidem quas et fugit aliquam. Repellendus temporibus molestiae quo incidunt repudiandae.\n\nEt culpa voluptatem nihil explicabo rerum nulla doloremque. Modi et illo architecto reiciendis et. Voluptatum impedit maiores ea dignissimos. Nulla animi exercitationem quaerat fugiat sit velit est.', 10, '2020-01-28 00:26:06', '2020-01-28 00:26:06', NULL),
(29, 'Vitae quo nulla.', 'Deserunt consequatur dolor officiis beatae rerum. Tenetur eum sed inventore adipisci quasi soluta voluptatem.\n\nEt et velit debitis placeat sed. Qui consequatur rerum esse aliquam aut alias aspernatur nisi. Excepturi voluptas impedit dolorem est nam similique ratione. Dignissimos ipsa et in soluta eveniet.\n\nEt accusamus aliquid illum illum ipsa. Et ab praesentium voluptas. Nostrum delectus consectetur qui est eveniet aut quod hic.\n\nQuidem dolor nobis aliquam dolore et. Voluptatem aliquid eum excepturi nesciunt reiciendis id facilis.\n\nVitae quia rerum quas alias qui ut qui alias. Cumque cupiditate id voluptatem sit tenetur aliquid labore.\n\nLaborum nesciunt cum possimus corrupti commodi excepturi. Exercitationem odit qui sit et et commodi voluptatum. Quod praesentium consectetur molestiae minima. Eos tenetur vero ea quia doloribus qui ut ipsa.\n\nOptio et maxime eum. Enim possimus ut et hic nesciunt saepe harum. Temporibus eaque doloremque tempore dicta autem rerum. Labore soluta possimus voluptate animi.\n\nSaepe laboriosam et blanditiis laborum a ut magni cupiditate. Consequatur quo illo est consectetur. Consequatur reprehenderit cupiditate vel sint et esse.', 10, '2020-01-28 00:26:06', '2020-01-28 00:26:06', NULL),
(30, 'Molestiae.', 'Et occaecati quibusdam corrupti asperiores quis. Enim minima rerum unde. Vel ea illum quia enim modi est est aspernatur. Autem beatae nobis neque placeat.\n\nRepellat reprehenderit dignissimos rerum tenetur. Quidem qui eligendi quos nesciunt quia numquam ea. Perferendis architecto deleniti excepturi voluptatem ut. Enim et et asperiores doloremque.\n\nIusto nostrum et consequatur inventore id quisquam cumque. Alias nostrum necessitatibus in magnam repellendus.\n\nRepellendus excepturi placeat reprehenderit omnis quia eaque. Necessitatibus enim id et earum neque vel quia. Ut porro provident aut voluptatum esse quia sapiente.\n\nUnde quo sit perferendis corporis. Porro ea ea laboriosam minima ab sequi est. Ut in mollitia veniam est delectus ullam. Magni aut quaerat sunt numquam.\n\nDolorum nam qui laboriosam sed hic quia dolor. Qui quae assumenda enim quam molestias voluptatibus. Totam suscipit reiciendis et sit ut consequatur sapiente. Quidem minima qui delectus sapiente repellendus et maxime et.\n\nSed sed assumenda ea ipsa rerum. Qui dolorem sit veritatis numquam. Iste sunt eligendi possimus dolores. Vitae ab aut sit odio.\n\nEum similique et inventore incidunt ad velit consequatur. Dolores et perferendis illo et in. Culpa blanditiis et sed cum nesciunt dolorem fuga.', 10, '2020-01-28 00:26:06', '2020-01-28 00:26:06', NULL),
(31, 'Voluptatem soluta.', 'Ut maiores aliquid minima eaque omnis aut et. Dicta velit quae quidem ea aut dolorem. Ex ea qui molestias numquam. Dicta aut molestiae nemo delectus nemo.\n\nQui quo autem est laudantium officiis. Omnis aut est mollitia ratione voluptatem eum aperiam asperiores. Possimus iste voluptate et consequatur commodi eligendi quo.\n\nQuod numquam est et. Ipsum voluptas doloremque possimus assumenda quia. Ut ea sed perspiciatis est. Fugit a nisi quae non.\n\nQuidem maiores reiciendis non ut corrupti aliquid. Vitae molestiae earum qui rerum totam nostrum. Pariatur voluptatibus animi quia cum officiis consectetur quos.\n\nRatione recusandae voluptatum aut qui est. Cumque expedita tempora laborum optio eos. Aliquid expedita quidem neque doloribus.\n\nPraesentium aliquid vel soluta quis. Omnis et dolorem dolorem perspiciatis reprehenderit. Excepturi sed libero eum et.\n\nFacere blanditiis exercitationem ut error. Rerum repellendus quo delectus dolore esse. Soluta sit ullam consequatur non est in modi architecto.\n\nNatus molestiae possimus voluptates. Minima est nisi est. Numquam aut sunt veritatis est. Placeat doloremque maiores deserunt est rerum exercitationem.', 11, '2020-01-28 00:26:06', '2020-01-28 00:26:06', NULL),
(32, 'Sit explicabo.', 'Sit a quis qui facilis. Sapiente incidunt ut facere exercitationem quia quos. Sunt qui provident sunt aut ut quibusdam. Aut id iure sint molestiae esse labore aut quaerat.\n\nDolorem ullam architecto sed nihil reiciendis. Aperiam similique sed et fuga. Corporis quibusdam ea cumque odio mollitia commodi quia. Occaecati aut ut nulla eum voluptas cum.\n\nBeatae pariatur doloribus dolores nam. Quo quo iusto voluptate reiciendis sit sit. Illum aut consequatur necessitatibus aliquid. Animi ea tenetur iure ut vel. Quis voluptas qui facere autem illum quisquam.\n\nEarum reprehenderit non veniam sint amet eligendi. Aut vel praesentium sit corporis tempore voluptas veniam similique. Quia laboriosam autem quia numquam.\n\nItaque est adipisci qui fugit repellat voluptas. Qui perferendis expedita tempora reiciendis. Nemo sint vitae natus. Officiis veritatis quidem iure qui voluptas non ad.\n\nAspernatur voluptates et nostrum fuga repellat. Accusamus et rerum voluptatem quasi et. Sunt similique ea recusandae cum tempore. Dignissimos quibusdam eius ut.\n\nLabore laudantium suscipit voluptas natus molestias eum. Nihil necessitatibus blanditiis officiis et. Ab exercitationem ad magnam perferendis.\n\nEt unde deleniti quod reiciendis quae facilis. Qui vel aut qui non rerum aspernatur. Est accusamus et nobis aliquam voluptas autem sint debitis. Sed sit autem quidem fugiat minima.', 11, '2020-01-28 00:26:06', '2020-01-28 00:26:06', NULL),
(33, 'Expedita cupiditate.', 'Ad laboriosam consequatur id alias quos. Distinctio at ut esse eius quo dolorem excepturi repellat. Quasi sequi molestiae quibusdam delectus voluptas commodi.\n\nIpsum ullam ducimus hic dignissimos aut. Quibusdam dolor modi et sit. Provident sunt iure adipisci ut eius pariatur.\n\nSed voluptatem qui reiciendis quasi praesentium occaecati nihil itaque. Ea perferendis in ipsam velit quidem non. Porro possimus sapiente perspiciatis consequatur maxime alias. Officia voluptatem nemo est nisi eos iure.\n\nQuasi possimus in et pariatur doloremque sit itaque. Fugit labore ab cum quo asperiores. Voluptatem odit quis cum ab non explicabo modi. Ea praesentium dignissimos assumenda nostrum.\n\nAut eos quibusdam necessitatibus ullam veritatis. Cupiditate quo placeat dolor assumenda repellendus nemo explicabo inventore. Quo eaque ut at qui eius nobis porro veritatis. Repudiandae sint qui cupiditate et recusandae iste ut.\n\nUnde aut libero voluptatum recusandae. Consectetur dolore asperiores dolor sit quos dolores voluptatibus. Est maxime totam non dolorem tempora excepturi. Nostrum quo repudiandae occaecati et qui reiciendis.\n\nAutem consequatur unde iure unde omnis. Et aut autem id expedita pariatur aspernatur. Earum dolor vel sit magni. Est a facere inventore.\n\nId id laborum rerum eaque. Et ab dignissimos non dolorem dicta. Sunt adipisci minima eligendi molestias minus autem. Laborum est ut eos aut.', 11, '2020-01-28 00:26:06', '2020-01-28 00:26:06', NULL);



CREATE TABLE `hidden_tweets` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `user_id` bigint(20) UNSIGNED NOT NULL,
  `tweet_id` varchar(255) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `users` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `username` varchar(30) NOT NULL,
  `email` varchar(50) NOT NULL,
  `twitter_username` varchar(255) DEFAULT NULL,
  `password` varchar(255) NOT NULL,
  `remember_token` varchar(100) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


INSERT INTO `users` (`id`, `username`, `email`, `twitter_username`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES
(1, 'federico', 'federico@federico.com', 'DpFederico', '$2y$10$hlhqFFS0Iu.ByblQbdDXZu2n9MuFzN0A7y8EtrPTfZEL00EVgTc8W', NULL, '2020-01-28 00:26:05', '2020-01-28 00:26:05'),
(2, 'conor37', 'rosalinda08@example.net', NULL, '$2y$10$ZfBryumBHB6grz2f3oen0.1gpjFscQ3WEzX6zqxsrsKupBHEBGwg.', NULL, '2020-01-28 00:26:05', '2020-01-28 00:26:05'),
(3, 'shyann08', 'judge.welch@example.org', NULL, '$2y$10$9gVaCjd4mis94U1UPpyB1.G.EfBzZj.MbmEHOsSeC34c0IqWMmrsa', NULL, '2020-01-28 00:26:05', '2020-01-28 00:26:05'),
(4, 'cummerata.shaun', 'bfeil@example.org', NULL, '$2y$10$UXHP7qnKfp7htyrxHj4OZOF1AbDv0iK900O2u64lY.SXeb7yLof0m', NULL, '2020-01-28 00:26:05', '2020-01-28 00:26:05'),
(5, 'padberg.gloria', 'lterry@example.org', NULL, '$2y$10$QdmXjk7XC7UoxlHJRcdtrehzFZ.YPjCTIjEARclrQ8vAoA.Cm4lYq', NULL, '2020-01-28 00:26:05', '2020-01-28 00:26:05'),
(6, 'kaylin.kirlin', 'chyna.hane@example.org', NULL, '$2y$10$jnmw0AxbLyVKcIWEdgPbo.OKC8t.xC5rGbg2g/M7I2Pmc6qKQZi8m', NULL, '2020-01-28 00:26:06', '2020-01-28 00:26:06'),
(7, 'madaline80', 'stehr.carmela@example.net', NULL, '$2y$10$zCnkX7LOVvVrqw3/Q30xxer.e4i4H9GKGVHtsS1Jtxft.SHR7Zc2e', NULL, '2020-01-28 00:26:06', '2020-01-28 00:26:06'),
(8, 'terry.bauch', 'hdonnelly@example.org', NULL, '$2y$10$cDVgjv3QDrjM0C7bdCwpfOCLTrvGghblKhk2dL04RN/zC63m6/6Ru', NULL, '2020-01-28 00:26:06', '2020-01-28 00:26:06'),
(9, 'dokeefe', 'xokuneva@example.net', NULL, '$2y$10$xOfOzSKpmHojDvECLJa3RegkTMQutuaiOl9RV.ynMpZh.5T/0dDom', NULL, '2020-01-28 00:26:06', '2020-01-28 00:26:06'),
(10, 'keebler.kathlyn', 'justyn58@example.org', NULL, '$2y$10$Hgj0HR.RfPDpcHGZuqxJNeZr3xXfEVZaJHg6WD.tm5kKPMWxl6gTm', NULL, '2020-01-28 00:26:06', '2020-01-28 00:26:06'),
(11, 'maggie.mosciski', 'halle43@example.org', NULL, '$2y$10$7ox8xlfYr1T3pX92mbdT8.BSmJev9eRll54tNp9EQ.FmgA4vgCPvu', NULL, '2020-01-28 00:26:06', '2020-01-28 00:26:06');


ALTER TABLE `entries`
  ADD PRIMARY KEY (`id`),
  ADD KEY `entries_user_id_foreign` (`user_id`);


ALTER TABLE `hidden_tweets`
  ADD PRIMARY KEY (`id`),
  ADD KEY `hidden_tweets_user_id_foreign` (`user_id`);


ALTER TABLE `users`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `users_username_unique` (`username`),
  ADD UNIQUE KEY `users_email_unique` (`email`);


ALTER TABLE `entries`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=34;


ALTER TABLE `hidden_tweets`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT;


ALTER TABLE `users`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=12;


ALTER TABLE `entries`
  ADD CONSTRAINT `entries_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`);


ALTER TABLE `hidden_tweets`
  ADD CONSTRAINT `hidden_tweets_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`);
COMMIT;

